version: '3'

services:
    db:
        image: postgres
        volumes:
            - ./tmp/db:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: password
    backend:
        build: 
            context: ./backend
            dockerfile: Dockerfile
        command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"
        #volumes:
        #    - $PWD:/backend
        ports:
            - "3001:3001"
        depends_on:
            - db
    frontend:
        build: 
            context: ./frontend
            dockerfile: Dockerfile
        command: npm start  
        #volumes:
        #    - '$PWD:/frontend'
        #    - '/frontend/node_modules'
        ports:
            - "3000:3000"   
        environment:
            - CHOKIDAR_USEPOLLING=true
        tty: true